### ISSUE TITLE
error: The 'pyneuroml==9999' distribution was not found and is required by neuronunit

### ISSUE THREAD

**Issue by JustasB** [scidash/neuronunit#101]
Using the latest version from dev branch, when i run `python setup.py install` I get the following message:

```
Installed /usr/local/lib/python2.7/dist-packages/pyNeuroML-0.3.0-py2.7.egg
error: The 'pyneuroml==9999' distribution was not found and is required by neuronunit
```
Seems like it's related to the following commit:
https://github.com/scidash/neuronunit/commit/ff86ebcd49a73dd429c95a81ca887095f5975efe

I get a similar message with latest dev install for **sciunit** as well:

```
Installed /usr/local/lib/python2.7/dist-packages/quantities-0.11.1-py2.7.egg
error: The 'quantities==999' distribution was not found and is required by sciunit
```

**Comment by russelljjarvis** [comment]
Yes, Rick has done this deliberately as a work around for satisfying dependencies in a way that meets his requirements.

The way to get around it is to use a pattern like (where RUN can be omitted in native BASH, and `WORKDIR` can be replaced with `mkdir` or `cd` (WORKDIR does both of these things depending on whether the directory already exists or not):

```
WORKDIR $HOME
RUN wget http://github.com/scidash/sciunit/tarball/dev -O sciunit.tar.gz
RUN mkdir -p sciunit
RUN tar -xvzf sciunit.tar.gz -C sciunit --strip-components=1
RUN rm sciunit.tar.gz
WORKDIR sciunit
RUN pip install --process-dependency-links -e .
WORKDIR $WORK_HOME
```

**Comment by JustasB** [comment]
Ok i see.

@russelljjarvis is the script something that is a workaround for now, or do you expect that this will need to be part of the install process for sci/neuronunit in the long run?

If long term, consider mentioning the script in install instructions, as most people will likely, like me, just run `python setup.py install` and run into the same problem -- which adds to the barrier to adoption of sci/neuronunit.

**Comment by russelljjarvis** [comment]
No Rick does not intend it for the long run, or even the next big release. Its just a development orientated work around. 

I forgot to say the only critical commands:

` pip install --process-dependency-links -e .`

with the -e functioning to add the path (a dev environment link) to the front of sys.path such that it has precedence, and the --process-dependency-links means don't act on the 999 packages, or use the latest versions. In fact I don't understand what it really means, I only understand that its a short term hack that is not intended for major releases.

**Comment by JustasB** [comment]
Alright - I see :)
