### ISSUE TITLE
unit_test/core_tests.py failing due to bbp url

### ISSUE THREAD

**Issue by JustasB** [scidash/neuronunit#102]
Using the latest dev version, when I run unit_test/core_tests.py locally, I see the following error:

```
[NbConvertApp] Converting notebook .\bbp.ipynb to python
[NbConvertApp] Writing 292 bytes to .\bbp.py
Getting data from http://microcircuits.epfl.ch/data/released_data/B95.zip
E[NbConvertApp] Converting notebook ../docs\chapter1.ipynb to python
[NbConvertApp] Writing 12223 bytes to ../docs\chapter1.py
=== Model my_neuron_model achieved score Pass on test 'my_average_potential_test'. ===
A boolean score. Must be True or False.
Converts a score to Pass if its value is within the range [-2,2], otherwise Fail.
True if the observation and prediction were sufficiently similar; False otherwise
.[NbConvertApp] Converting notebook .\get_tau.ipynb to python
[NbConvertApp] Writing 1866 bytes to .\get_tau.py
Estimated tau = 6.845 ms; Actual tau = 7.0 ms
.Getting None data values from neuroelectro.org
http://www.neuroelectro.org/api/1/nedm/?e=2&n=72&pmid=18667618
Getting input resistance data values from neuroelectro.org
http://www.neuroelectro.org/api/1/nes/?e=2&e__name=input+resistance&n__name=Dorsal+root+ganglion+cell&n=72
.
======================================================================
ERROR: test_bluebrain (core_tests.BlueBrainTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "core_tests.py", line 63, in test_bluebrain
    self.do_notebook('bbp')
  File "C:\Users\Justas\AppData\Local\conda\conda\envs\p2\lib\site-packages\sciunit-0.1.5.8-py2.7.egg\sciunit\utils.py", line 154, in do_notebook
    self.convert_and_execute_notebook(name)
  File "C:\Users\Justas\AppData\Local\conda\conda\envs\p2\lib\site-packages\sciunit-0.1.5.8-py2.7.egg\sciunit\utils.py", line 115, in convert_and_execute_notebook
    exec(code,globals())
  File "<string>", line 13, in <module>
  File "C:\Users\Justas\AppData\Local\conda\conda\envs\p2\lib\site-packages\neuronunit-0.1.8.9-py2.7.egg\neuronunit\bbp.py", line 38, in get_curated_data
    data = get_sweeps(url, sweeps=sweeps)
  File "C:\Users\Justas\AppData\Local\conda\conda\envs\p2\lib\site-packages\neuronunit-0.1.8.9-py2.7.egg\neuronunit\bbp.py", line 50, in get_sweeps
    path = find_or_download_data(url) # Base path for this data
  File "C:\Users\Justas\AppData\Local\conda\conda\envs\p2\lib\site-packages\neuronunit-0.1.8.9-py2.7.egg\neuronunit\bbp.py", line 75, in find_or_download_data
    with zipfile.ZipFile(downloaded_file,"r") as zip_ref:
  File "C:\Users\Justas\AppData\Local\conda\conda\envs\p2\lib\zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "C:\Users\Justas\AppData\Local\conda\conda\envs\p2\lib\zipfile.py", line 813, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file

----------------------------------------------------------------------
Ran 4 tests in 7.199s

FAILED (errors=1)
```

Looking closer, it looks like the test tries to get the following url: `http://microcircuits.epfl.ch/data/released_data/B95.zip`, which appears to be broken (403 forbidden).

Strangely, travis-ci is did not complain about this url 7 days ago, so either the url broke since then or it could also be just my machine problem.

**Comment by rgerkin** [comment]
I'd have to imagine the URL broke.  Every now and then one of the tests fails because neuroelectro is down, too.  At the very least it lets me know to check the URL and email the site maintainers.  In fact, since you found it, I delegate that task to you @JustasB.

**Comment by russelljjarvis** [comment]
I also have about 4/5 success rate with querying neuroelectro.

**Comment by JustasB** [comment]
It looks like the whole BBP site is down/non functional - no contact information anywhere. Here's the screenshot of the home page:

![image](https://user-images.githubusercontent.com/10732358/30222685-7b9493f8-947c-11e7-8f0d-1f46e618b444.png)

Together with the problems with neuroelectro, as well as this BBP website, we would benefit from separating the following two concerns:

- Testing whether code under our control is still working as expected (new bugs have not been introduced to previously working code)
- Checking whether an external resource is available

I agree that it's nice to know from running unit tests if an external resource is unavailable. However, we should separate that concern from the code testing concern for the following reasons. 

1. If unit tests start failing after a dev makes a code change, s/he knows that his/er change broke it, and s/he can fix it, ensuring that anyone else after her/im, can rely on the unit tests to isolate problems with their code.
2. There are much better, free tools for availability polling. Availability checking using unit tests will only catch problems when the unit test suite is run. If there are days or weeks in between code changes -- down times could go undetected for that long. For example, StatusCake.com, can be used to continuously monitor a url for downtime, and be notified via email when it happens. If we chose to use them, we could embed uptime widgets (see example below) for neuroelectro, BBP, and any other external resources on the main github page, next to the "build pass/fail" widgets.

Here's an example widget for one of the NML-DB.org pages: 

<a href="https://www.statuscake.com" title="Website Uptime Monitoring"><img src="https://app.statuscake.com/button/index.php?Track=0r6A35al1v&Days=1000&Design=4" /></a>

**Comment by JustasB** [comment]
Additionally, we could modify the unit tests that rely on external resources so that the resources are pre-downloaded, and the unit test code checks our code against the cached version of the resource. 

Of course the external resource could change, which would break our code even if no code has changed, but that's a larger problem similar to the problem of what happens when external libraries change (eg neo 0.4->0.5) which also breaks our code.

**Comment by rgerkin** [comment]
These are good ideas, @JustasB.  I've added a new issue (#105) to deal with these things.
