### ISSUE TITLE
inject_current interface needs to be standardized

### ISSUE THREAD

**Issue by JustasB** [scidash/neuronunit#11]
The [ReceivesCurrent](https://github.com/scidash/neuronunit/blob/dbee6e6c91813af5766a6bd83e932bda0bd91d1a/neuronunit/capabilities/__init__.py#L88) capability defines an interface method inject_current, which expects the _current_ parameter to be a neo.core.AnalogSignal. 

```
class ReceivesCurrent(Capability):
	"""Indicates that somatic current can be injected into the model."""
	
	def inject_current(self,current):
		"""Injects somatic current into the model.  
	    Parameters
	    ----------
	    current : neo.core.AnalogSignal
	    This is a time series of the current to be injected.  
	    """
		
		raise NotImplementedError()
```
However, all of the other classes and examples pass in dictionary objects instead, whose keys and values vary across models.

For example, in [neuronunit/tests](https://github.com/scidash/neuronunit/blob/dbee6e6c91813af5766a6bd83e932bda0bd91d1a/neuronunit/tests/__init__.py#L118) it passes in a dictionary:

```
{'amplitude':-10.0*pq.pA, 'delay':100*pq.ms, 
				 'duration':500*pq.ms}}
```
Furthermore, in [neuronunit.neuroconstruct.capabilities](https://github.com/scidash/neuronunit/blob/bfa08358385a9dd0b066c6667fb06719a24f45c5/neuronunit/neuroconstruct/capabilities.py#L137), 'ampl' key is used instead of 'amplitude':

```
cmd += 'err = j.sim.set_current_ampl(%f);' % injected_current['ampl']
		cmd += 'channel.send(err);'
```
Then in the [ReadMe](https://github.com/scidash/neuronunit/blob/c809b88f89aee652bea2fc613fafac26cb0d8659/README.md#L105) and in [Chapter 3](https://github.com/scidash/neuronunit/blob/dbee6e6c91813af5766a6bd83e932bda0bd91d1a/docs/chapter3.ipynb#L151), the dictionary values do not use units:
```
params={'injected_current':{'ampl':0.0053}}) # 0.0053 nA (5.3 pA) of injected 
```
and
```
params={'injected_current':{'ampl':0.006}}) # 0.0053 nanoamps of injected 
```

Since everything already uses dictionaries with similar forms, I propose that the inject_current method interface be changed to accept a dictionary of the following form and include units:
```
{'amplitude':-10.0*pA, 'delay':100*ms, 'duration':500*ms}}
```
This will require modifying:

- [ ] inject_current method comments
- [ ] neuronunit.neuroconstruct.capabilities
- [ ] The ReadMe example
- [ ] Chapter 3 example

**Comment by JustasB** [comment]
Why is this a problem: In the current situation, different types of models would have to specify the same current injection protocol in slightly different parameter formats. If the interface was standardized then a suite of models and current injection requiring tests could reuse the same current parameter.

Furthermore,  if everyone follows the defined interface, then when developing new models, the new developers would not have to be concerned with what is being passed into the inject_current method.

**Comment by rgerkin** [comment]
@JustasB I agree, a dictionary with the keys you specified is what I ultimately ended up using for everything else, and I failed to fix those other things.  I will take care of that now.

**Comment by rgerkin** [comment]
Fixed in d804608 and cf24c7a.  I ended up making inject_current take an AnalogSignalArray, and inject_square_current take a dictionary.

**Comment by JustasB** [comment]
Awesome, thank you

**Comment by rgerkin** [comment]
Couple of bug fixes left to work out...

**Comment by rgerkin** [comment]
OK, everything seems to run now, at least in the Izhikevich model notebook.

**Comment by rgerkin** [comment]
And in the Travis tests.
