### ISSUE TITLE
Create weighted, pooled summary observations

### ISSUE THREAD

**Issue by rgerkin** [scidash/neuronunit#13]
This will require:  
- [ ] a new subclass of `neuroelectro.NeuroElectroData` corresponding to these weighted summaries
- [ ] a new `neuroelectro_pooled_observation` method for `tests.VmTest`

These should use the API to take each `NeuroElectroDataMap`, and compute a weighted mean, with the weights proportional to the reciprocal of the squared standard error.  Note that the reported SD for a given data map may in some cases actually be an SE (does the API tell you if this is the case?).  So if it is an SD, then w = N/(SD^2), and if it is already an SE than just w=1/SE^2.

**Comment by JustasB** [comment]
Hmm, it looks like the API does not disambiguate SEs from SDs. From @stripathy:

> If you look at the summary spreadsheet here: http://neuroelectro.org/static/src/article_ephys_metadata_curated.csv, you'll see 6 terms per ephys property, for example for rmp: (rmp rmp_raw rmp_err rmp_n rmp_sd rmp_note). The n term is provided by the authors and the sd term is converted from the standard error (err) term provided by the authors.
> 
> In terms of the api, we only export the n and error terms (we don't disambiguate whether the error is a standard error or a SD).

**Comment by stripathy** [comment]
Good point @JustasB - I'll add a field to the api that allows you to disambiguate whether the errors are SD or SEM.

**Comment by JustasB** [comment]
@stripathy Let us know when the SD/SEM flag is ready -- I have everything in place on our side to look for the flag.

However works for you, but it would work for me if it was something along the lines of:

![screen shot 2016-05-28 at 8 28 35 am](https://cloud.githubusercontent.com/assets/10732358/15628139/b7d0c07e-24ae-11e6-9fa2-bbe88f622ca6.png)

**Comment by rgerkin** [comment]
@JustasB @stripathy I implemented most of the API so I think it might be faster if I figure this one out (unless you have someone on it already, Shreejoy), but it will probably have to wait a few days.

**Comment by JustasB** [comment]
Sounds good guy, whatever works for you

**Comment by stripathy** [comment]
Hi @rgerkin and @JustasB - I'll take care of this tomorrow before leaving town. It's super simple on my end, I just need to add a field to the DB indicating what the error type is and then do a migration.

**Comment by stripathy** [comment]
I just implemented this feature as requested. You'll now see a field called "error_type" on nedm data objects indicating the error type. http://dev.neuroelectro.org/api/1/nedm/?n=129

Please note that we're using a computational method to "guess" what the error type is (based on the size of the errors relative to the mean across all the data extracted for each article) vs manually curating whether errors are SDs vs SEMs. If you come across papers where the imputed error type is wrong, please let me know.

<img width="232" alt="screen shot 2016-06-06 at 4 51 57 pm" src="https://cloud.githubusercontent.com/assets/2458713/15841589/490e0f42-2c07-11e6-9b4b-5bea30c8314a.png">

**Comment by JustasB** [comment]
Thanks @stripathy 

For the error type, when I looked at the MC data, the err or err_norm value (if existed) always corresponded to the SEM. However in the API, its not always SEM. Thoughts?

This is where I talk about it always being SEM:

https://github.com/neuroelectro/neuroelectro_org/issues/290#issuecomment-222321866

**Comment by rgerkin** [comment]
@JustasB Did you ever implement this?

**Comment by JustasB** [comment]
@rgerkin The functionality to compute grand means and SDs from individual paper means and sds has been implemented in neuronunit:

https://github.com/scidash/neuronunit/blob/feb7e80bbbd7bf203f424e6d223f2c31a1a134d6/neuronunit/neuroelectro.py#L271

@stripathy implemented the change to return the error type:
https://github.com/scidash/neuronunit/issues/13#issuecomment-224123763

and neuronunit code is using the error types of each paper to determine the grand mean and sd.
