### ISSUE TITLE
.travis.yml unit testing on test specific branch working (minimally)

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/neuronunit#131]
branch is called test_branch
https://travis-ci.org/russelljjarvis/neuronunit
TODO:

    silence date time warnings (warnings.filter) does not work, by copying custom ipyparallel.util file.

    make minor fixes, that are required to make unit_test cases pass.

    about 50% pass, some fail for environment dependent reasons.

**Comment by rgerkin** [comment]
What is the status now?
