### ISSUE TITLE
Exhaustive search generates iterator, computes rheobase, but then hangs.

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/neuronunit#134]
After spending some time investigating this issue, I am starting to think that there might be problems to do with simultaneous file writing in get_neab.py. It is well documented that simultaneous parallel file writing leads to thread lock, and not only that these operations are unnecessary anyway. I will try to change the use and implantation of get_neab to stop threadlocking. Also it is unclear how and why the NSGA GA avoids these issues.

**Comment by rgerkin** [comment]
So you are saying that the GA doesn't hang but exhaustive search does due to this issue?

**Comment by russelljjarvis** [comment]
I believe so, although that defies common sense because the GA is more complex.

**Comment by russelljjarvis** [comment]
[This](https://github.com/russelljjarvis/neuronunit/tree/functional) code works better. It errors for a different reason (capabilities/spike_functions reasons), where I accidentally changed the capabilities/spike_functions.py code as I was not installing                       'neo==0.5.2' by default.

I do not understand the critical difference between russelljarvis/functional and scidash/test_branch but I believe running a diffing program over them should help.

**Comment by rgerkin** [comment]
@russelljjarvis What is the status of this?

**Comment by russelljjarvis** [comment]
Fixed ages ago.
