### ISSUE TITLE
Serialization test on master not working anymore

### ISSUE THREAD

**Issue by gidili** [scidash/neuronunit#140]
Hi @rgerkin - was looking at the [sample serailization test](https://github.com/scidash/neuronunit/blob/master/neuronunit/unit_test/serialization_test.ipynb) you pointed us to to check for any json changes but the sample is not loading anymore. I am assuming due to the changes you were mentioning... can you have a look or point us to another up to date example?

**Comment by rgerkin** [comment]
Could you describe the error you are getting?  The changes I mentioned was in the .xml file being used, but that is only in the non-master branches.  As far as I can see, the serialization notebook still runs fine in the master branch.

**Comment by gidili** [comment]
@rgerkin weird it was showing a message "could not load" now back to normal. Probably a github issue 🙈 I'll close this. Is the development branch a good place to grab the most recent json?
