### ISSUE TITLE
Standardize indentation across all .py files

### ISSUE THREAD

**Issue by JustasB** [scidash/neuronunit#15]
Python is a white-space sensitive language and mixing tabs with spaces for indentation results in syntax errors. We should agree on a convention for indentation, and use it throughout. 

I propose that we use "4 spaces per indentation level" for all python files. E.g. one 1 TAB = 4 SPACES.

Using spaces will result in unambiguous indentation, while tabs may be system dependent. The popular code editors allow setting space/tabs preference.

If this is agreeable, I can convert the existing indentation to spaces in all .py files in the repo. However, to minimize merging issues, this should be planned to be done at a point when everyone has checked in their changes.

**Comment by rgerkin** [comment]
@justasb I agree, I think Cyrus has been using 2 spaces in some cases and I never converted it over.  If you want to run every file through an automated PEP-8 stylizer, or do it manually, go for it.

**Comment by cyrus-** [comment]
Yeah I'm not sure why I used 2. Feel free to change.

**Comment by JustasB** [comment]
This has been implemented in the PR above
