### ISSUE TITLE
resolve git history

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/neuronunit#151]
Resolve my own personal git history problems that are stopping me from merging: 
```-b results russelljjarvis/neuronunit into -b dev russelljjarvis/neuronunit ```

**Comment by rgerkin** [comment]
Let's take a look at this in person today and I can show you my strategies for this.

**Comment by russelljjarvis** [comment]
Sorry I was not available today. I gave a presentation for an ethics class which involved a lot of preparation, it was a once in semester type thing, so I am free now. I am working on this issue again now however.
