### ISSUE TITLE
Lazy parallelization

### ISSUE THREAD

**Issue by rgerkin** [scidash/neuronunit#152]
https://tdhopper.com/blog/parallelizing-a-python-function-for-the-extremely-lazy/

**Comment by rgerkin** [comment]
@russelljjarvis Check this out.

**Comment by russelljjarvis** [comment]
Looks okay, but it seems like it needs to be invoked from BASH, which is one of the down sides of ipyparallel. I can imagine gnuparallel coming in handy for other routine jobs though.

**Comment by russelljjarvis** [comment]
dask does not need bash invocation.
