### ISSUE TITLE
Add RRID to neuronunit page (github and scidash.org)

### ISSUE THREAD

**Issue by rgerkin** [scidash/neuronunit#154]

**Comment by russelljjarvis** [comment]
Scicrunch resolver is where you find the RRIDs:
https://scicrunch.org/resolver
| SciUnit, RRID:SCR_014528 |  
| NeuronUnit, RRID:SCR_015634 |
| neuroelectro (RRID:SCR_006274)  |


![rrids](https://user-images.githubusercontent.com/7786645/35175219-db79f72e-fd2f-11e7-8557-2b9b26e540e7.png)

The Allen Brain has several tools registered with RRIDs only one of them mentions an API, I think thats the one that is relevant to ours.
| Allen Brain Atlas API (RRID:SCR_005984) |

**Comment by rgerkin** [comment]
Implemented in cde4991398353dcbe6349913cd97fe91c6c85146, etc.
