### ISSUE TITLE
unit tests of neuronunit tests fail with serial NEURON

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/neuronunit#156]
unit tests of neuronunit tests fail with serial neuron because the latest backends no longer refreshes neuron models with current injection.

serial rheobase unit test not working with serial neuron as model,  /model/backends.py is no longer 

refreshing the neuron model between runs as you would expect

adding in the line    `self.init_backend()` at 515 of backends.py  eg:

works.

``` python
    def inject_square_current(self, current, section = None):

        self.init_backend()
```

**Comment by russelljjarvis** [comment]
This issue is resolved but not in the most 'maintainable', way. I welcome suggestions on a more transparent fix.

``` python.
        ##
        # init_backend is the most reliable way to purge existing NEURON simulations.
        # however we don't want to purge the model attributes, we only want to purge
        # the NEURON model code.
        # store the model attributes, in a temp buffer such that they persist throughout the model reinitialization.
        ##
        temp_attrs = copy.copy(self.model.attrs)
        self.init_backend()
        self.set_attrs(**temp_attrs)
```

**Comment by rgerkin** [comment]
Fixed with `self.init_backend()`, which purges the information associated with a previous simulation.
