### ISSUE TITLE
Network based neuronunit tests and data to inform the construction of such tests.

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/neuronunit#176]
For the ICON lab hackathon it is desirable for some data to be digitised to inform network wide sciunit tests. I propose measuring multivariate spike distance (a-synchrony),  Spike Train Distance.
Data for entrorhinal cortex at the bottom of this paper: https://www.sciencedirect.com/science/article/pii/S0165027007002671 It would be great if someone who needs a task could digitize it.

In the future it might be desirable to make multivariate transfer entropy tests too.

**Comment by rgerkin** [comment]
I don't think the CV data was meant as a network test, but it is a good data to use with the CV tests you have already created for single neurons.

**Comment by russelljjarvis** [comment]
Yes, makes sense.
