### ISSUE TITLE
Model validation

### ISSUE THREAD

**Issue by gidili** [scidash/neuronunit#186]
Neuronunit should expose wether a given model instance can implement the capabilities of that model class

**Comment by gidili** [comment]
The logic of finding appropriate xml tags related to capability implementation should be separated form manipulating values associated to those tags.

We need a way to tell that a given model instance can implement the capabilities guaranteed by the model class. 

For example as a usecase in scidash we need to be able to populate model classes as the creates a model instance:
<img width="929" alt="screenshot 2018-08-01 17 53 33" src="https://user-images.githubusercontent.com/68134/43536306-2e85b332-95b4-11e8-83b5-e56ced0a4126.png">

**Comment by rgerkin** [comment]
Partly implemented in 7952585e8459fc10d36918663a443fdad2ceb91b

**Comment by gidili** [comment]
Request: .check will default to False (instead of True) so that we know that a particular model instance does not implement a given capability.

**Comment by rgerkin** [comment]
Added in scidash/sciunit@cca66d0 an keyword argument `require_extras` to all `check` and `check_capabilities` methods to require that instance level methods to check for capability implementation exist (and return True) for a capability to be considered implemented.
