### ISSUE TITLE
Implement all Druckman Tests

### ISSUE THREAD

**Issue by rgerkin** [scidash/neuronunit#190]
Implement tests for all 38 of the features used in [Druckman et al](https://doi.org/10.1093/cercor/bhs290), shown here: https://academic.oup.com/view-large/80919724

**Comment by JustasB** [comment]
Full list:

- [ ] Drop in AP amplitude (amp.) from first to second spike (mV)
- [ ] AP amplitude change from first spike to steady-state (mV)
- [ ]  AP 1 amplitude (mV)
- [ ]  AP 1 width at half height (ms)
- [ ]  AP 1 peak to trough time (ms)
- [ ]  AP 1 peak to trough rate of change (mV/ms)
- [ ]  AP 1 Fast AHP depth (mV)
- [ ]  AP 2 amplitude (mV)
- [ ]  AP 2 width at half height (ms)
- [ ]  AP 2 peak to trough time (ms)
- [ ]  AP 2 peak to trough rate of change (mV/ms)
- [ ]  AP 2 Fast AHP depth (mV)
- [ ]  Percent change in AP amplitude, first to second spike (%)
- [ ]  Percent change in AP width at half height, first to second spike (%)
- [ ]  Percent change in AP peak to trough rate of change, first to second spike (%)
- [ ]  Percent change in AP fast AHP depth, first to second spike (%)
- [ ]  Input resistance for steady-state current (Ohm)
- [ ]  Average delay to AP 1 (ms)
- [ ]  SD of delay to AP 1 (ms)
- [ ]  Average delay to AP 2 (ms)
- [ ]  SD of delay to AP 2 (ms)
- [ ]  Average initial burst interval (ms)
- [ ]  SD of average initial burst interval (ms)
- [ ]  Average initial accommodation (%)
- [ ]  Average steady-state accommodation (%)
- [ ]  Rate of accommodation to steady-state (1/ms)
- [ ]  Average accommodation at steady-state (%)
- [ ]  Average rate of accommodation during steady-state
- [ ]  Average inter-spike interval (ISI) coefficient of variation (CV) (unit less)
- [ ]  Median of the distribution of ISIs (ms)
- [ ]  Average change in ISIs during a burst (%)
- [ ]  Average rate, strong stimulus (Hz)
- [ ]  Average delay to AP 1, strong stimulus (ms)
- [ ]  SD of delay to AP 1, strong stimulus (ms)
- [ ]  Average delay to AP 2, strong stimulus (ms)
- [ ]  SD of delay to AP 2, strong stimulus (ms)
- [ ]  Average initial burst ISI, strong stimulus (ms)
- [ ]  SD of average initial burst ISI, strong stimulus (ms)

The details of each test are here:
[bhs290supp.pdf](https://github.com/scidash/neuronunit/files/2295064/bhs290supp.pdf)

**Comment by JustasB** [comment]
These have been implemented and tested with all NeuroML-DB.org cell models. 

All tests can be found here: https://github.com/scidash/neuronunit/blob/dev/neuronunit/tests/druckmann2013.py

**Comment by russelljjarvis** [comment]
That is quiete a lot of tests. 

I wonder if some of the tests are dependent on others?

For example in the 8 tests I use to optimize, 4 are spike measurements, and they depend on knowing the rheobase current injection.

I think that we such dependancies need to be reflected in the OOP design somehow. Ie many tests inherit from a base VMtest, if a subset of these tests depend on rheobase being known, this subset should inherit from RheobaseTest too.

**Comment by JustasB** [comment]
I think what you describe is a perfectly fine way to design a class hierarchy.

@russelljjarvis Take a look at the class diagram for these tests:

[druckmannClassUML.zip](https://github.com/scidash/neuronunit/files/2621630/druckmannClassUML.zip)

When designing the inheritance hierarchy, I was working with the following challenges:

- Many test aspects had to be writen to match the specific way the properties were computed in the original paper (I could only reuse some of the previously written NU utility methods)
 - Many tests described in the paper, re-used methods across the tests (I wanted to avoid duplicated code)
 - Almost all the tests assumed that the RB is already known (its multiple is passed in as a test parameter)
 - Some of the tests computed the same AP property for the second instead of first AP (I wanted to avoid duplication again)
 - Some of thet tests repeated an existing test, but with different amount of current (but need a way to reflect that in test name and NU description tags)
 - Some of the tests used results of multiple previous tests

My solution was to use inheritance whenever a test was a variation on an earlier test, or composition of test instances when multiple previous tests were used.

**Comment by russelljjarvis** [comment]
I have been playing around, with using the Druckman test suite with the optimizer. As I think its really good to have all of these new NU tests available.

I have noticed that there is a class that may need instancing (note I renamed the file `druckmann2013.py` as just dm. So I do this:
 ```
from neuronunit.tests import dm #import VmTest
dmtests = dm.Druckmann2013Test()
```
but I need to supply a current amplitude.
```
TypeError: __init__() missing 1 required positional argument: 'current_amplitude'
```
Is this current amplitude some multiple of rheobase (like 1.5)? I have noticed that many Druckman tests or on multiple spike waveforms. I will recommend some minor changes in a pull request over the hackathon.

**Comment by rgerkin** [comment]
@russelljjarvis @JustasB I agree this will be a great thing to test and iron out during the hackathon.

**Comment by JustasB** [comment]
For [input resistance](https://github.com/scidash/neuronunit/blob/dev/neuronunit/tests/druckmann2013.py#L778), the parameter should suppy an array of at least two negative currents. 

For tests that have "[StrongStim](https://github.com/scidash/neuronunit/blob/dev/neuronunit/tests/druckmann2013.py#L1385)" in their name, the parameter should be 3x the rheobase current.

For all other tests, the parameter should be 1.5x the RB

**Comment by russelljjarvis** [comment]
Cool, good to know.

Also @JustasB what is your opinion about chattering or bursting neurons. Neurons, that are either silent, or fire a burst, but they never fire exclusively once. Should they be eligible to take these tests too?

The reason I ask, is my rheobase search algorithm will exclude such models, and either excluding 'no-rheobase' or accepting such models, could be important to code design.

**Comment by rgerkin** [comment]
@russelljjarvis As previously written, your code would look for the minimum current to evoke *exactly* one spike, but as you may recall we fixed this a few months ago to be the minimum current to evoke *at least* one spike (or at least it was fixed in one branch at some point).  So it should work for all models that are capable of spiking and capable of not spiking, even if there is a discontinuity from, say, 0 spikes to 10 spikes.  

Whether this is the kind of model neuron we are dealing with is handled by another test ([Threshold Firing Test](https://github.com/scidash/neuronunit/blob/master/neuronunit/tests/dynamics.py#L13)), which should probably be rewritten to just reuse the F/I data from the Rheobase test to save compute time.

**Comment by JustasB** [comment]
I'm thinking we would need either experimental data from real cells to compare against models, or values obtained from complex models that can then be used to compare to reduced models.

**Comment by russelljjarvis** [comment]
In the two lists below, I think that accommodation, and adaption, are referring to same concept.

Both lists contain multiple measurements of AHP.

This is a list of all the neuroElectro electro-physiological ontologies:
```
cell capacitance
input resistance
resting membrane potential
membrane time constant
spike amplitude
spike half-width
spike threshold
rheobase
firing frequency
AHP duration
cell diameter
access resistance
sag ratio
cell surface area
AHP amplitude
FI slope
spontaneous firing rate
fast AHP amplitude
fast AHP duration
slow AHP amplitude
slow AHP duration
spike width
ADP amplitude
ADP duration
spike peak
adaptation ratio
first spike latency
other
spike rise time
spike decay time
spike max rise slope
spike max decay slope
sag amplitude
maximum firing rate
medium AHP amplitude
medium AHP duration
spike amplitude from resting
spike amplitude from trough
AHP voltage
fast AHP voltage
slow AHP voltage
medium AHP voltage
AHP amplitude from resting
fast AHP amplitude from resting
slow AHP amplitude from resting
medium AHP amplitude from resting
adaptation ratio (last/first ISI)
adaptation percent (first/last ISI)
adaptation percent (last/first ISI)
adaptation ratio (1 – first/last ISI)
```
And this is all the Druckman tests you have implemented:
```
AP12AmplitudeDropTest(standard), 
    AP1SSAmplitudeChangeTest(standard), 
    AP1AmplitudeTest(standard), 
    AP1WidthHalfHeightTest(standard), 
    AP1WidthPeakToTroughTest(standard), 
    AP1RateOfChangePeakToTroughTest(standard), 
    AP1AHPDepthTest(standard), 
    AP2AmplitudeTest(standard), 
    AP2WidthHalfHeightTest(standard), 
    AP2WidthPeakToTroughTest(standard), 
    AP2RateOfChangePeakToTroughTest(standard), 
    AP2AHPDepthTest(standard), 
    AP12AmplitudeChangePercentTest(standard), 
    AP12HalfWidthChangePercentTest(standard), 
    AP12RateOfChangePeakToTroughPercentChangeTest(standard), 
    AP12AHPDepthPercentChangeTest(standard), 
    AP1DelayMeanTest(standard), 
    AP1DelaySDTest(standard), 
    AP2DelayMeanTest(standard), 
    AP2DelaySDTest(standard), 
    Burst1ISIMeanTest(standard), 
    Burst1ISISDTest(standard), 
    InitialAccommodationMeanTest(standard), 
    SSAccommodationMeanTest(standard), 
    AccommodationRateToSSTest(standard), 
    AccommodationAtSSMeanTest(standard), 
    AccommodationRateMeanAtSSTest(standard), 
    ISICVTest(standard), 
    ISIMedianTest(standard), 
    ISIBurstMeanChangeTest(standard), 
    SpikeRateStrongStimTest(strong), 
    AP1DelayMeanStrongStimTest(strong), 
    AP1DelaySDStrongStimTest(strong), 
    AP2DelayMeanStrongStimTest(strong), 
    AP2DelaySDStrongStimTest(strong), 
    Burst1ISISDStrongStimTest(strong),
    Burst1ISIMeanStrongStimTest(strong)]
```

**Comment by russelljjarvis** [comment]
I think we should rename the file Druckman measurements. A different file that merges the measurements with appropriate falsifying data would be called Druckman measurements.

**Comment by russelljjarvis** [comment]
I wouldn't say this is done, as the tests are still measurements, but they could be upgraded to tests.

**Comment by rgerkin** [comment]
@russelljjarvis Which file are you talking about?

**Comment by russelljjarvis** [comment]
neuronunit/neuronunit/tests/druckmann2013.py

My mistake, it's not the file that would need renaming but this GitHub issue.

**Comment by rgerkin** [comment]
I renamed the issue, but I'm confused about the other part.  That file already contains many test classes, does it not?  For example, in the dev branch, `AP12AmplitudeDropTest` subclasses `Druckmann2013Test` subclasses `VmTest`.

**Comment by russelljjarvis** [comment]
Yes, but I think the measurements are just inheriting useful class properties, like `generate_prediction` etc. I don't think there is any sciunit/neuronunit level testing going on, and I think it's important to be unambiguous with language, in these contexts.

**Comment by rgerkin** [comment]
@russelljjarvis OK, you're probably right, I may not have looked closely enough.  
@JustasB I know you're just using parts of the test infrastructure here -- what do you propose these be called?  I recognize this is sort of duplicating the same question across issues, but I'm hoping the "answer" will become clear if we see the question in different contexts.

**Comment by russelljjarvis** [comment]
I think you could even reopen the issue, but change the name again, to 'upgrade Druckmann measurements to tests'. The issue was initially an announcement, that the measurements were implemented, but the issue changed in nature, to instead reflect, given that the measurements exist how to convert them to tests.

**Comment by rgerkin** [comment]
I think this will be handled in the implementation of #75.

**Comment by JustasB** [comment]
They seem to squawk, walk, and smell like tests to me -- so I think they're tests. If they're included in a suite, and provided with data to compare against, they'll return test results just like the other tests. What am I missing?

**Comment by russelljjarvis** [comment]
Maybe its just a semantic thing, but I feel like a test, that other people can pick up and start using, is a package that includes the data, and the generate_prediction method together. That is the case for the other NU tests I have been using. If the data is not included a method for downloading it is.

I think the only missing ingredient is the data or the methods for downloading and aligning the appropriate data.

**Comment by rgerkin** [comment]
But `VmTest` (which these tests subclass) does implement the methods for getting data (from NeuroElectro), so what do these Druckmann test classes not have that others do?  Tests were called tests in NeuronUnit long before get_neab.py.

**Comment by russelljjarvis** [comment]
Okay, so what should you call packaged tests then?, Like if you wanted to use language really precisely to avoid ambiguity. Like tests that are ready for user consumption?

**Comment by rgerkin** [comment]
There has never been a class for packaged tests.  There are instances of tests classes, where those instances use specific data as observations, is that what you mean?  

And I disagree that an end user could/would never use a Druckmann test.  For example, Druckmann used them (albeit not in NeuronUnit).

**Comment by russelljjarvis** [comment]
yes, I think when there is observations, that is test (comparison) not just a measurement. I guess I evaluated all the druckmann tests at one point, and then I got confused. I thought I was testing, as opposed to measuring, but where were the scores?

Maybe it has changed since then?

**Comment by JustasB** [comment]
I think there are three different aspects here: a) the stimulation protocol b) the algorithm to compute the property value and c) comparison of the value to what's seen experimentally. All tests in NU provide a and b. The user has to supply c from e.g. literature or neuroelectro. 

In case of druckmann properties, those values are not available anywhere, but in theory, someone could subject real cells to the same protocols, compute the properties, and then supply their values to the druckmann NU tests for comparison. But this last act of measuring them would not change the code on NU.

**Comment by russelljjarvis** [comment]
Yes, I agree that tests can mean 'a', 'b' and 'c'.  I was thinking I can just disambiguate in my own code, by labelling test classes that are prepackaged with falsifying data as: 'ExecutableTests', tests that are ready to be taken.

I just checked the definition of the word test. It has two definitions, the first is a noun the second is a verb. I guess I had always thought about NU tests as acting like the verb meaning, but I think that the class that becomes incrementally constructed is more like a noun.

**Comment by russelljjarvis** [comment]
I was thinking more about the relationship of Druckmann (DM) tests and VmTest, to scientific unit-testing. I think the relationship is that DM test, and VmTest are both necessary but not sufficient, to do scientific unit-testing. So a good name could also be `VmTestComponents`, and `DMTestComponents`. Also I realised that I can show that the DM tests can in principal work with optimization, if data existed, by creating fake observations, from models evaluated at random data points, and to use optimizer learned knowledge of error gradients to blindly recover, the random data points.

**Comment by rgerkin** [comment]
What is sufficient?  The test plus the observed data?  Because that is what you usually get when you instantiate a test (except that Druckmann and TestM2M because they are purely for generating model output and/or comparing it against other models, rather than against data)?

**Comment by russelljjarvis** [comment]
I think the test+observed data, is sufficient for making an executable scientific unit-test. If there are exceptions to this, I wonder if a few words sentences could explain to the Test user, a test class is sometimes a component of a test, were test is meant in the noun sense. Instanced tests are often executable, and then they become comparisons (test is meant in the verb sense).

**Comment by rgerkin** [comment]
Since a normal `Test` is instantiated with data, then the resulting instance is sufficient to meet your vision of the scientific unit test.  

But it is clear that we have a few cases where people are interested in using the Test's methods for something other than comparison to data.  So there may be a need for a less hack-y way of doing that, such as a top-level class in SciUnit which is like a protocol.  `Test`, `TestM2M`, and Justas' use case for Druckmann "tests" could all derive from that.  As we work with HBP over the next year, I think we will figure out what works best.  I don't want to pick the answer quite yet.

**Comment by russelljjarvis** [comment]
Yes, maybe the answer will emerge from continued community use and participation. The user market might decide.
