### ISSUE TITLE
sciunit.log depreciated?

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/neuronunit#196]
Does sciunit still have a log function?
This line breaks code, in my current version. The line only gets executed given exceptional circumstances, so unit testing might not pick it up.
https://github.com/scidash/neuronunit/blob/master/neuronunit/capabilities/spike_functions.py#L90

**Comment by rgerkin** [comment]
Possibly fixed in scidash/sciunit@49e4789e4bd97c0dd5dd7d04eb0b988fc8e48077.
