### ISSUE TITLE
Could not find a version that satisfies the requirement sciunit-9999 (from neuronunit==0.19)

### ISSUE THREAD

**Issue by gidili** [scidash/neuronunit#197]
Hi @rgerkin, we are getting this on local install using 'dash' branches of sciunit and neuronunit:

<img width="878" alt="screenshot 2019-02-13 13 04 40" src="https://user-images.githubusercontent.com/68134/52713712-ef1d1480-2f8f-11e9-9616-383a3503b4e0.png">

Dev branch seems to be ok. 

Hopefully it's something simple that slipped into this branch?

**Comment by rgerkin** [comment]
@gidili I just committed a fix to dash branch, but it (as in dev branch) requires that you use pip >=18.1, since it uses PEP 508 URL dependencies (the only sane way to avoid problems like the one above).

**Comment by gidili** [comment]
Thanks @rgerkin! I've already upgraded pip, will give it a go first thing
in the morning.

cc @nezanyat
