### ISSUE TITLE
Way to check class capabilities without instantiating it

### ISSUE THREAD

**Issue by NeZanyat** [scidash/neuronunit#203]
Sometimes I need to retrieve capabilities from model but I don't need to instantiate it, I used some generic model file, but it's not always works with some models. Is there a way to do this?

**Comment by NeZanyat** [comment]
To retrieve capabilities I use capabilities property.

**Comment by rgerkin** [comment]
The current `capabilities` attribute is an instance-level attribute, but looking at [the code](https://github.com/scidash/sciunit/blob/dev/sciunit/models/base.py) it could be made class-level by removing __class__ from the one line in that capabilites method.

**Comment by NeZanyat** [comment]
Could I change it in dash branch?

**Comment by rgerkin** [comment]
Yes, go ahead.  Open a PR and I will approve it.

**Comment by rgerkin** [comment]
Implemented in #212.
