### ISSUE TITLE
Enable daily Travis CI builds

### ISSUE THREAD

**Issue by JustasB** [scidash/neuronunit#215]
**Background**
Whenever a Travis build fails, it can be difficult to determine if the failure is due to the code that was just checked in or due to a change in some external dependency (e.g. an update to a pip package or unavailability of some resource). Scheduled builds could help determine the cause.

**Proposal**
I propose we enable daily scheduled Travis CI builds. This can be done via [Travis Cron job ](https://docs.travis-ci.com/user/cron-jobs/) settings. 

**Expected result**
The scheduled builds would run every 24 hours and if it fails one can inspect Travis CI build history and see one of the following:

- Previous checked-in build **succeeded**, but the scheduled build **failed**: Indicates an issue with an external dependency
- Previous checked-in build **failed** and so did the **scheduled** build: The failure is probably caused by the earlier checked-in code

**Comment by rgerkin** [comment]
Good idea.  I've just added weekly ones to master and dev branches of both sciunit and neuronunit.  I don't want to do daily at the moment since some of the external resources (like neuroelectro) time out periodically and I don't want to get an email every time this happens.
