### ISSUE TITLE
No units, observation and params schema in test

### ISSUE THREAD

**Issue by NeZanyat** [scidash/neuronunit#218]
Observations is required, but there is no schema for them, I can't show the UI without this schema. Same with units and params. 

https://github.com/scidash/neuronunit/blob/dash/neuronunit/tests/channel.py#L15

**Comment by rgerkin** [comment]
Fixed in 510e18dbcd239629302a60c475fbb467a0267b43 and scidash/sciunit@41b2e38c45c0776727ab1f281a572b65be19cea1

**Comment by gidili** [comment]
Hey @rgerkin I see the commit are on dev, are they also merged into dash?

@NeZanyat can you test this after it's merged to dash branch and if so let us know if we can close the issue?

🙏

**Comment by rgerkin** [comment]
Ah, sorry, dev is the most up to date.

**Comment by rgerkin** [comment]
dash and dev are now identical as of this moment, so you can test in dash and see if any changed pulled in from dev have changed anything.
