### ISSUE TITLE
create branch optimization based on dev, that I can merge pull requests into.

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/neuronunit#254]
create branch optimization based on dev, that I can merge pull requests into.

**Comment by rgerkin** [comment]
@russelljjarvis Done.

**Comment by russelljjarvis** [comment]
AOK, I am about ready to PR into that branch. One problem. I have been doing Continuous Integration, and I have about 25 commits that are package management, related and I want to squash.

Doing ```git rebase -i HEAD~25```, sort of seems to work, except that it burdens me with manual merges for every commit squash (up to 20 or so merges of the same files). 

Do you know any good alternatives?

I think github PR now comes with merge squash on your end. Would that work for you?
