### ISSUE TITLE
Docker build NU replication of AIBS.ipynb scipy/optomize/minpack is given parameters it can't optomize.

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/neuronunit#37]
In an attempted docker build replication of the AIBS notebook scipy/optomize/minpack is given parameters it can't optimize.

See the error messages below:

  check_error = suite.judge(model)
  File "/opt/conda/lib/python3.5/site-packages/sciunit/__init__.py", line 430, in judge
    deep_error=deep_error)
  File "/opt/conda/lib/python3.5/site-packages/sciunit/__init__.py", line 302, in judge
    raise score.score # An exception.  
  File "/opt/conda/lib/python3.5/site-packages/sciunit/__init__.py", line 296, in judge
    score = self._judge(model, skip_incapable=skip_incapable)
  File "/opt/conda/lib/python3.5/site-packages/sciunit/__init__.py", line 239, in _judge
    prediction = self.generate_prediction(model)
  File "/opt/conda/lib/python3.5/site-packages/neuronunit/tests/__init__.py", line 215, in generate_prediction
    tau = self.__class__.get_tau(vm, i)
  File "/opt/conda/lib/python3.5/site-packages/neuronunit/tests/__init__.py", line 163, in get_tau
    coefs = cls.exponential_fit(region, i['delay'])
  File "/opt/conda/lib/python3.5/site-packages/neuronunit/tests/__init__.py", line 175, in exponential_fit
    popt, pcov = curve_fit(func, x-offset*pq.s, y, [0.001,2,y.min()]) # Estimate starting values for better convergence
  File "/opt/conda/lib/python3.5/site-packages/scipy/optimize/minpack.py", line 680, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 800.

**Comment by russelljjarvis** [comment]
If this proves not to be an artifact of exclusively my code/contributions then it is probably caused by the factor of 10 error in the `get_tau` method of file neuronunit/tests/__init__.py

**Comment by rgerkin** [comment]
@russelljjarvis I am having difficulty locating a cause of the factor of 10 issue.  A factor of 1000 would be attributable to wrong choice of units (e.g. pA vs nA), but a factor of 10 is hard to fathom.

**Comment by russelljjarvis** [comment]
If this is only occurring in my NEURON implementations, and not your older `AIBS.ipynb` notebooks which used JNeuroML/LEMSmodel the old way, its probably something wrong with my implementation between the files:

https://github.com/russelljjarvis/neuronunit/blob/dev/neuronunit/tests/NeuroML2/LEMS_2007One_nrn.py#L138-#L172

https://github.com/russelljjarvis/neuronunit/blob/dev/neuronunit/models/backends.py#L124

It could be that the time step `dt` is not the expected one, such that the resulting time recorded vector is dilated or contracted, or that the line [in](
https://github.com/russelljjarvis/neuronunit/blob/dev/neuronunit/tests/NeuroML2/LEMS_2007One_nrn.py):

`py_v_time = [ float(t) for t in h.v_time.to_python() ] # Convert to Python list for speed...`
Should read:
`py_v_time = [ t/10.0 for t in h.v_time.to_python() ]  # Convert to Python list for speed...`

**Comment by russelljjarvis** [comment]
bump.

**Comment by rgerkin** [comment]
As you said, I could easily imagine that the error might have been introduced with the NEURON implementation by not taking into account the size of the time step, which might have been something like 0.1 ms but was taken to be 1 ms.  I was getting reasonable scores with default model parameters in my original implementation that just ran through jNeuroML.

**Comment by russelljjarvis** [comment]
Yes, I believe it. I will try to address this soon.

Actually regarding your original code, I tried to revisit it about 2 months ago, by visiting all the really old commits in the AIBS.ipynb.

I never did manage to get the original back, because it requires matching up the older AIBS.ipynb with the older scidash/neuronunit 

But running the original is something I would find useful too, also so I can find out objectively just how slow it really was.

**Comment by russelljjarvis** [comment]
Alright so I tried addressing this this issue.

Its true that making adjusting dt from `0.0025ms` to `0.025ms` removes the need to divide by 10, but the actual NeuroML/XML code everything is derived from specifies a time step of `0.002ms`

<Simulation id="sim1" length="1600ms" step="0.0025ms" target="net1">

Voltage traces from `dt=0.025ms` look realistic to me however, and everything runs 10* faster (again) so I am inclined to leave things this way at least to debug some other parts of the program.
