### ISSUE TITLE
PyNeuroML->JNeuroML->NEURON is very slow.

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/neuronunit#38]
Could this process be sped up? Can we stop NMODL mechanisms being re-compiled on subsequent invocations of NEURON?

**Comment by pgleeson** [comment]
@russelljjarvis There are some optimisations that are there already in this pipeline, e.g. if jNeuroML generates a string for a mod file that is identical to an existing file, it doesn't write it and so nrnivmodl doesn't need to recompile it. This doesn't work if the code gets generated into a new directory every time though.. 

Do you have a short script example that shows what you need to do and what needs to be sped up?

**Comment by russelljjarvis** [comment]
I didn't expect to actually get an answer and I didn't realize this was actually an active area of development. Basically I am trying to replicate some of [this](https://github.com/rgerkin/IzhikevichModel/blob/master/AIBS.ipynb) notebook using a dockerbuild that is underdevelopment. 

Its probable that jNeuroML generates a string for a mod file that differs from previous runs, and I just didn't understand what was going on. Sorry.

In the file[ `simple.py`](https://github.com/russelljjarvis/sciunitop/simple.py) I have removed most of the testing from `AIBS.ipynb` example except for a test that searches for Rheobase.

Recreating this build environment is currently a bit lengthy, and I wouldn't expect that level of support.  However a pre built Docker image should be available soon. When I run build the Dockerfile in the repository:
And then run inside that directory run: 
`sudo docker run -v `pwd`:/home/mnt -it deapscoop1 bash`
and then run 
`simple.py`
This results in many calls with stdout:
`pyNeuroML >>>   jNeuroML >>  (INFO) Successful compilation`

**Comment by rgerkin** [comment]
@russelljjarvis @pgleeson Unfortunately I think currently I am using the LEMS template to write a new file into a new directory each time.  The code for generating the random temp directory is here: 
https://github.com/scidash/neuronunit/blob/dev/neuronunit/models/__init__.py#L54
I don't know if this is what is meant above, but it could probably be sped up by caching hashes of some of the previously generating files, along with the corresponding temp directories, and then just using the same temp directories when the same hash is encountered.

**Comment by russelljjarvis** [comment]
Yes, thats what I meant. I will pursue it in the future.

**Comment by pgleeson** [comment]
Possible ways to speed it up would be to restructure so the code gets written into the same temp directory (only possible if one run will be fully finished /analysed before another runs) and that the same LEMS file is used every time, with just a change in the nml files. Then if the channel files are the same in subsequent runs the mod files won't be rewritten and nrnivmodl will run faster.

Alternatively, you could go even faster if you just generate the Neuron code once, and directly modify the values in Neuron & rerun. The gen code consists of a Python class and are methods in it like run(), save_results() etc. which can be used to control the simulation... Less simulator independent but probably faster...

**Comment by russelljjarvis** [comment]
Yes I am taking the approach described in your second paragraph. I think it is much faster so far, the only problem is making this work in a way that can generalize to other models
For example the file that is made by JNeuroML: ```LEMS_2007One_nrn.py```
makes the current electrode source:

```
h("objref explicitInput_RS_IextRS_pop0")
h("RS_pop[0] { explicitInput_RS_IextRS_pop0 = new RS_Iext(0.500000) } ")
```
I wonder if the variable for a current source in the pyhoc generated by jNeuroML will always start with 
```explicitInput_RS_Iext```? 

If so I might be able to check if that name exists in the hoc name space and do something in python like: 

```electrode=[ i for i in dir(h) if i==str('explicitInput_RS_Iext') ][0]```

**Comment by rgerkin** [comment]
@russelljjarvis 
Have you looked at the things Justas did in `neuronunit/neuron`?  That was originally done to allow him to run things directly in NEURON (and not via jNeuroML), but it would be worth taking a look at to avoid duplicating too much effort.  

Also I implemented dynamic selection and switching of backends in 17ec613.

**Comment by russelljjarvis** [comment]
Oh No! I have not looked. I hate duplication of effort. I will look now.
