### ISSUE TITLE
code stubs.

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/neuronunit#43]
So I think the code stubs you made for me to complete are here:
https://github.com/scidash/neuronunit/blob/dev/neuronunit/models/backends.py

But that I also may need to massage these files:
https://github.com/scidash/neuronunit/blob/dev/neuronunit/models/reduced.py

https://github.com/scidash/neuronunit/blob/dev/neuronunit/models/__init__.py

Also I will test out reproducing AIBS.ipynb soon such that I can close previous issues.

**Comment by rgerkin** [comment]
Yes, you shouldn't really need to change `__init__.py`, but let me know if you do.  As for `reduced`, I think you can add a version of `ReducedModel` that uses the `NEURONBackend`, but I am going to work on making it so the backend is something you can pass to the constructor.

**Comment by russelljjarvis** [comment]
Okay, as usual I found it easier to write a template outside the class definitions.

Starting from the environment defined by the AIBS.ipynb import statements. If you insert this code near the top it will:

1. As a once off, translate the neuroml file LEMS_2007One.xml  to a NEURON simulation in a python file.

2. Loads the contents of the file into memory (initializes the model).

3. Provides a way of updating the model parameters (but not yet the stimulation protocol).

So its just a matter of working this into your stubs in the OOP framework, and also providing the stimulation protocal. 

Also it would be nice if it cached the nml->pyhoc conversion such that it only has to do this once ever. I will try to borrow from your latest code that does this with the allensdk related nwb files.



```
def init_nrn_model():#do this once only.
    '''
    Take a declarative model description, and convert it into an implementation, stored in a pyhoc file.
    import the pyhoc file thus dragging the neuron variables into memory/python name space.
    Since this only happens once outside of the optimization loop its a tolerable performance hit.
    '''
    #could this be a shorter root to NeuroML2/LEMS_2007One.xml saving the user from needing to supply it given NeuroML2 may already be installed?
    #izc=nml.nml.Izhikevich2007Cell
    IZHIKEVICH_PATH = os.getcwd()
    LEMS_MODEL_PATH = os.path.join(IZHIKEVICH_PATH,'NeuroML2/LEMS_2007One.xml')                        
    # github.com/OpenSourceBrain/IzhikevichModel.
    DEFAULTS={}
    DEFAULTS['v']=True
    pynml.run_lems_with_jneuroml_neuron(LEMS_MODEL_PATH, 
                                      skip_run=False,
                                      nogui=False, 
                                      load_saved_data=False, 
                                      plot=False, 
                                      show_plot_already=False, 
                                      exec_in_dir = ".",
                                      only_generate_scripts = True,
                                      verbose=DEFAULTS['v'],
                                      exit_on_fail = True)
    init_nrn_model()

def update_nrn_param(param_dict):
    #TODO find out the python3 syntax for dereferencing key value pairs.
    #Below syntax is stupid, but how to just get key generically without for knowledge of its name and without iterating?
    key=[ key for key in param_dict.keys() ][0]
    value=[ value for value in param_dict.values() ][0]
    print(key)
    print(value)
    pdb.set_trace()
    evalstring='neuron.hoc.execute("m_RS_RS_pop[0].'+str(key)+'='+str(value)+'")'
    eval(evalstring)
    neuron.hoc.execute('forall{ psection() }')
   
from NeuroML2 import LEMS_2007One_nrn     
from NeuroML2.LEMS_2007One_nrn import NeuronSimulation
neuron.load_mechanisms(os.getcwd()+'/NeuroML2')
ns = NeuronSimulation(tstop=1600, dt=0.0025)
neuron.hoc.execute('forall{ psection() }')
neuron.psection(neuron.nrn.Section())
param_dict={}
for vr in np.linspace(-75,-50,6):
    param_dict['vr']=vr               
    update_nrn_param(param_dict)
```

**Comment by russelljjarvis** [comment]
Basic idea is demonstrated here:
https://github.com/russelljjarvis/IzhikevichModel/blob/dev/AIBS_fast.ipynb

**Comment by russelljjarvis** [comment]
This file is part of the way there:

https://github.com/scidash/neuronunit/blob/dev/neuronunit/models/backends.py

I am trying to get your file Optimization.ipynb to work by calling NEURON as discussed. But its a lot of work actually.

I converted the notebook to a plain *.py file and its located in the directory below

My current build pattern uses the dockerfile here:
https://github.com/russelljjarvis/neuronunit/tree/dev/neuronunit/software_tests

Which does have some subtle but effective differences mainly in that it tends to draw on my own source code which is not good enough to pullrequest yet, but hopefully will be with your help :)
https://github.com/russelljjarvis/sciunit/tree/dev

**Comment by rgerkin** [comment]
I added dynamic specification of backends in 17ec613.  

You shouldn't be reimplementing things like `get_spike_train` or `get_spike_count` in your `NEURONBackend`.  These should be simulator-independent things that only rely on simulator-dependent things like `get_membrane_potential`.  Once you implement the latter, you should get the former for free, provided that your `get_membrane_potential` adheres the specifications (i.e. it returns a `neo.AnalogSignal`.  

Also, you shouldn't need to use `eval`, e.g. 
```
evalstring='self.neuron.hoc.execute("m_RS_RS_pop[0].'+str(key)+'='+str(value)+'")'
eval(evalstring)
```

should just be:
```
self.neuron.hoc.execute("m_RS_RS_pop[0].'+str(key)+'='+str(value)+'")
```

But I assume you did it for a reason.  Why isn't it working without `eval`?

**Comment by russelljjarvis** [comment]
Yes, you are right there is no reason why not to use `self.neuron.hoc.execute` instead of `eval(string)`. I have heard that using pythons reflection is bad design so I will change it over. My reason was only that it was a fast and dirty approach that worked faster at the time. Thats great about dynamic specification of backends. I will change the code such `get_spike_train` and `get_spike_count` are inherited. I just wanted to explore if using NEURON directly was significantly faster, so I provided those things temporarily to get a glimpse of what that would be like.

**Comment by russelljjarvis** [comment]
It can pass the Rheobase test now (but without using inheritance properly dynamic specification). I will pull your changes. Merge and fix this inheritence issue. Also I will replace as much of my code as possible with Justa's implementation, since his code is quiete good.

**Comment by russelljjarvis** [comment]
Hi @rgerkin , In response to 

> I added dynamic specification of backends in 17ec613.

https://github.com/russelljjarvis/neuronunit/blob/dev/neuronunit/software_tests/Optimize.py

I have merged those changes, and re-factored the code such ```NEURONBackend``` inherits from ```ReducedModel``` And then I made everything work again, so it does optimization now of the ```Rheobase test``` again except via NEURON.

There were a few problems and issues that come up during the process.
```
https://github.com/russelljjarvis/neuronunit/blob/dev/neuronunit/models/backends.py
```

First I don't know the correct way to make NEURONbackend overwrite [ReducedModels](https://github.com/russelljjarvis/neuronunit/blob/dev/neuronunit/models/reduced.py#L48) version of the method ```inject_square_current```

Second I had to edit models `__init__.py` to make it such that it did not call jNeuroML to invoke the NEURON simulator everytime (as opposed to just modifying the model stored in memory as discussed). I don't think you will like the way that I am doing it.

https://github.com/russelljjarvis/neuronunit/blob/dev/neuronunit/models/__init__.py#120

Third I think there is a bug in sciunits get tau (get the membrane time constant?)

https://github.com/russelljjarvis/neuronunit/blob/dev/neuronunit/tests/__init__.py#L167

I think cls.exponential fit wants arguments a and b to both be sequences, but as my code runs only 
region is  i['delay'] is scalar (its something like 100 qt ms)
```              #coefs = cls.exponential_fit(region, i['delay'])```

Finally I will I keep working on improving the style to make it more readable, and I will keep trying to replace my code with Justas' pre-established methods wherever possible.

**Comment by rgerkin** [comment]
@russelljjarvis 
Is this still an issue for you?

**Comment by russelljjarvis** [comment]
Sort of yes and no. It no longer generates the curve fiitting error cited above, as I fixed the code with some [hacks](https://github.com/russelljjarvis/neuronunit/blob/compare_justas/neuronunit/tests/__init__.py#L239-L253), where I added missing `compute_score` methods to the TimeConstant test and CapacitanceTest classes.

And [here]([hacks](https://github.com/russelljjarvis/neuronunit/blob/compare_justas/neuronunit/tests/__init__.py#L280-L290).

I also made shore a lot of the time qt.units were consistently set to ms, the result was still a time constant computation that was a factor of ten too large so I divided it by 10 [here](https://github.com/russelljjarvis/neuronunit/blob/compare_justas/neuronunit/tests/__init__.py#L239-L253).

So now the Z-scores seem appropriate, but it would be good if I did not have to do the manual divide by 10

**Comment by russelljjarvis** [comment]
I will create a new issue for it on my branch. 
Also I am not sure if you noticed but I did complete your speed up time ___ 
stubs. However what I wrote may have been buried in a lot of other thoughts too.

**Comment by rgerkin** [comment]
Solved.
