### ISSUE TITLE
off by one type error.

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/neuronunit#44]
I was wondering if you could enable issues for [your IzhikevichModel](https://github.com/rgerkin/IzhikevichModel/blob/master/Optimize.ipynb) repository:

``

This is 7 Elements for `nu_tests`
```
est_class_params = [(nu_tests.InputResistanceTest,None),
                     (nu_tests.TimeConstantTest,None),
                     (nu_tests.CapacitanceTest,None),
                     (nu_tests.RestingPotentialTest,None),
                     (nu_tests.InjectedCurrentAPWidthTest,None),
                     (nu_tests.InjectedCurrentAPAmplitudeTest,None),
                     (nu_tests.InjectedCurrentAPThresholdTest,None)]
```
So I think the nested clause should read  `for i in [4,5,76]:`
```
def update_amplitude(test,tests,score):
    rheobase = score.prediction['value']
    for i in [5,6,7]:
```

Also different minor fix in the same file:
Technically using neuron as a variable name works out fine in the below:
```neuron = {'nlex_id': 'nifext_50'} # Layer V pyramidal cell```
Since the way Justas and I am using the neuron module is by making it a class attribute, however I think this clash has the potential to cause havoc in the future. Maybe we could call it `nlexid` or `neurolex`?
I think it only reappears one other time in that file. Also the AIBS.ipynb file may contain the same off by one type error.
```observation = cls.neuroelectro_summary_observation(neuron)```

**Comment by rgerkin** [comment]
@russelljjarvis 
But the rheobase test gets prepended to that, becoming item 0, so I think the current numbering is correct.

**Comment by rgerkin** [comment]
Issues enabled.

**Comment by russelljjarvis** [comment]
Yes you are right, I was confused because I had edited out one of the list elements without updating the for loop, and forgetting that I had made those changes at all.
