### ISSUE TITLE
Error importing jnml from nml

### ISSUE THREAD

**Issue by travs** [scidash/neuronunit#6]
When I try to run `from neuronunit.nml import jnml` I get an import error, to do with LEMS.

This seems to be because [LEMS/run.py](https://github.com/LEMS/pylems/blob/master/lems/run.py) has no `run` function. Maybe I am using the wrong version of pylems?

@rgerkin 
[**Full output**](http://hastebin.com/ipahimiboh.python)

**Comment by rgerkin** [comment]
@travs Fixed in rgerkin/neuronunit but scidash/neuronunit is still behind.  I will manually merge this later as we both independently added setup.py scripts (I accepted your pull request and patch scidash/neuronunit soon with my other commits).
