### ISSUE TITLE
Idea for even greater speed up on NSG 

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/neuronunit#63]
@rgerkin 

When you think about it, all the tests in suite judge should be run in parallel, since they are all a bit slow and often involve more simulations/current injections.

The general idea is 
```
score = get_neab.suite.judge(model)#passing in model, changes model
```
Should be replaced with: 

```
def test_to_model(local_test_methods,model):
    import matplotlib.pyplot as plt
    local_test_methods.judge(model)
    local_test_methods.tests.related_data['vm'].rescale('mV')
    plt.plot(model.results['t'], model.results['vm']
    plt.clf()
    return model.results
local_test_methods = [ i.judge for i in get_neab.suite.tests ]
judged = futures.map(test_to_model,local_test_methods,repeat(model))
```
Whether or not this works probably depends on if we have really succeeded in making neuronunits test __init__.py object pickable, but its something you should look in to if you have the time.

from scoop import futures

**Comment by russelljjarvis** [comment]
The following pattern works when called in serial (using fall back to regular python map). It does not work in parallel due to the error below:
```
def test_to_model(local_test_methods,model):
    import matplotlib.pyplot as plt
    model.re_init(model.attrs)
    local_test_methods(model)
    print(local_test_methods)
    plt.plot(model.results['t'], model.results['vm'])
    plt.savefig(str(local_test_methods)+str('.png'))
    plt.clf()

    return model.results


def build_single(indexs):
    attrs,name,rheobase=indexs
    from scoop import futures
    model.attrs=attrs
    model.update_run_params(attrs)
    model.update_run_params(model.attrs)
    model.name = str(attrs)
    get_neab.suite.tests[0].prediction={}
    get_neab.suite.tests[0].prediction['value']=rheobase*qt.pA
    judged = list(futures.map(test_to_model,local_test_methods,repeat(model)))
```
stderr
```
    for key in self.unpicklable:
AttributeError: 'RheobaseTest' object has no attribute 'unpicklable'
/opt/conda/lib/python3.5/site-packages/matplotlib/__init__.py:1350: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.
```

**Comment by rgerkin** [comment]
Before going any further in this direction, I want to understand why we should expect parallelizing the inside of the test suite to confer any advantage over just parallelizing the parameter search, given a fixed number of cores.  Is there any reason to think that cores are sitting around unused if we don't parallelize inside the test suite?  

As for the error, I can only imagine it results from the InputResistanceTest constructor not calling the [sciunit.SciUnit constructor](https://github.com/scidash/sciunit/blob/dev/sciunit/__init__.py#L42).  I'm not sure why that is happening in serial but not in parallel.  Or maybe in parallel when it unpickles that attribute disappears somehow, because it is not actually defined as an attribute of the class anywhere, only initialized in the constructor.  Maybe you can try adding `unpicklable` as an attribute to the `sciunit.SciUnit` class, i.e. `unpicklable = None` outside the constructor, just in the body of the class definition (and make sure to use that version of `sciunit`).

**Comment by russelljjarvis** [comment]
Its not happening in serial because its only parallel mapping (future mapping that pickles), its iwith out `futures.map` it just falls back to map which has no need to pickle. Pickling is used to collate results spread out across different CPUs onto rank 0

I think there is an advantage in spreading out the work load when ever a call to NEURON is involved. 

Timing would be the only way to find out if this approach has real merit or not.

**Comment by russelljjarvis** [comment]
More on this issue. If you look at SCOOPs logo, a tree or a graph, you can actually see that the philosophy of SCOOP is about nested parallel calls. The easiest way to think about what I am proposing is that calls to futures.map inside futures.map is causing a branching and tree like network topology (its not a persistent topology, it only exists for the duration of the the nested calls to futures.map. The 'O' in or the root, is more like a broker, but sometimes its behaves like a serial processor as all the results are mapped back to it.

![image](https://cloud.githubusercontent.com/assets/7786645/24830965/065da1ec-1c45-11e7-8b3e-9838a4d17d07.png)

I guess my belief that the work loads will get done faster if jobs are spread out across the leaves of a tree (a hierarchal spread as opposed to just spread a flat spread) is only motivated by the philosophy of SCOOP. It may not actually be merit based.

**Comment by rgerkin** [comment]
Did you try the idea to list `unpicklable` explicitly as an attribute of `sciunit.SciUnit`?

**Comment by russelljjarvis** [comment]
I found where the unpicklable list was initialized as empty list inside an abstract base class inside sciunit. I thought from previous conversations the idea was to append things to this list. Presumably to append them to the list after the base classes object instances are made, and not inside the class definition code itself. 

This is not an area that I have a lot of experience with and I can't really pretend to understand how this works.

**Comment by rgerkin** [comment]
Closing since we decided to focus on ipyparallel.
