### ISSUE TITLE
Get Singularity image built and running on NSG/XSEDE resources

### ISSUE THREAD

**Issue by rgerkin** [scidash/neuronunit#64]
- [ ] Build a Singularity version of the Docker image and run it successfully on your local machine
- [ ] Upload that image to an XSEDE machine (e.g. Comet) and get it to run there.

**Comment by russelljjarvis** [comment]
Plans, manually upload data to Comet using web portal, launch job from webportal.

Launch this command with the singularity image using a command such as:
[nu.def](https://github.com/russelljjarvis/neuronunit/blob/dev/neuronunit/tests/singularityimage/)

```sudo singularity bootstrap pnp_latest-2017-05-19-f1d9712ba440.img nu.def```

See if I can configure the launch of singularity+Comet to basically execute that statement, using `pnp_latest-2017-05-19-f1d9712ba440.img nu.def`, which I will manually upload to the portal.

**Comment by russelljjarvis** [comment]
bump. ^^

**Comment by russelljjarvis** [comment]
Using the pattern:
http://singularity.lbl.gov/docs-docker
```
sudo singularity create --size 4000 tensorflow.img
sudo singularity import tensorflow.img docker://tensorflow/tensorflow:latest
```

```
sudo singularity import pnp.img docker://pnp
library/pnp:latest
```
```
sudo singularity create --size 4000 pnp.img
sudo singularity import pnp.img docker://pnp
```

Causes the error below:
```
Error getting tags using url https://registry-1.docker.io/v2/library/pnp/tags/list
Bootstrap initialization
No bootstrap definition passed, updating container
Executing Prebootstrap module
Executing Postbootstrap module
ERROR: Container does not contain the valid minimum requirement of /bin/sh
```
This has been fixed in the development branch of singularity:
https://github.com/singularityware/singularity/issues/421
Which probably involves building it from source.

**Comment by rgerkin** [comment]
On my Mac I had this problem (long irrelevant code blocks replaced by `...`): 

```
vagrant@vagrant-ubuntu-trusty-64:~$ sudo singularity create --size 10000 neuronunit.img
Creating a new image with a maximum size of 10000MiB...
...
Done.
vagrant@vagrant-ubuntu-trusty-64:~$ sudo singularity import neuronunit.img 
...
Extracting /home/vagrant/.singularity/docker/sha256:7719a427e59f2abb32c0722f1bfb670a6c4a7339c0e8d2fffc19a8eb3ae2d606.tar.gz
tar: opt/conda/lib/icu/current: Cannot create symlink to ‘56.1’: File exists
tar: Exiting with failure status due to previous errors
ERROR:python:Error extracting image: /home/vagrant/.singularity/docker/sha256:7719a427e59f2abb32c0722f1bfb670a6c4a7339c0e8d2fffc19a8eb3ae2d606.tar.gz
ERROR: Aborting with RETVAL=1
```

**Comment by rgerkin** [comment]
@russelljjarvis 
But it looks like Singularity 2.3 has now been released (as of May 31st) so if I rename my old `singularity-vm` directory, and then do:  

```
mkdir singularity-vm
cd singularity-vm
vagrant init singularityware/singularity-2.3
vagrant up
vagrant ssh
```
i.e. Option 1 on the Mac instructions [page](http://singularity.lbl.gov/install-mac)

then inside the Vagrant container do:  
`singularity --version` (should be 2.3 with some suffix)
then do: 
```
singularity create --size 10000 neuronunit.img
singularity import neuronunit.img docker://scidash/neuronunit:latest
```

It seems to complete without error.  Then I do:  
```singularity shell neuronunit.img```

and

```
python -c "import neuronunit"
```

and it seems to work.

**Comment by russelljjarvis** [comment]
AOK.

**Comment by rgerkin** [comment]
Probably not useful in light of so many HPC resources providing Docker support.
