### ISSUE TITLE
As is the backends file is still probably calling jNeuroML unnecessarily.

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/neuronunit#65]
To eliminate unnecessary jNeuroML calls for all subsequent model instantiations.

Lines 252-252 of [model/backends.py](https://github.com/scidash/neuronunit/blob/dev/neuronunit/models/backends.py#L252-L253) should be updated to contain the two extra lines below.

```
        sort_file_path, _ = self.orig_lems_file_path.split("/LEMS_2007One")
        sort_file_path, _ = os.path.splitext(sort_file_path)
        architecture = platform.machine()
        NEURON_file_path = os.path.join(sort_file_path,architecture)
```

The code works otherwise but its probably slower.

**Comment by rgerkin** [comment]
@russelljjarvis 
This and some of the code in the few dozen lines above it are still model specific (referring to LEMS_2007One and such).  Can this section be made model-independent by having it determine the name of that directory from some other attribute of the model (like the orig_lems_file_path, for example).

**Comment by russelljjarvis** [comment]
The problem in this specific case is that the path `self.orig_lems_file_path` looks like:
```
/neuronunit/tests/NeuroML2/LEMS_2007One.xml/x86_64
```
but we actually just want:
```
/neuronunit/tests/NeuroML2/x86_64
```
Maybe instead of using the commands below, I can find a command that simply takes an absolute file path and returns just the directory that contains that file.
```
   sort_file_path, _ = self.orig_lems_file_path.split("/LEMS_2007One")
   sort_file_path, _ = os.path.splitext(sort_file_path)
```
I guess we could check for the x86_64 subdirectory by recursively searching. 


/neuronunit/tests/NeuroML2/LEMS_2007One.xml/x86_64

**Comment by russelljjarvis** [comment]
Just ignore this thread. I think some of my confusion comes from a git merge I completed. There is old code that you wrote that used to find the directory that contains the file, but it got buried somehow. I will check older commits.
