### ISSUE TITLE
Move to neo 0.5

### ISSUE THREAD

**Issue by appukuttan-shailesh** [scidash/neuronunit#68]
I was taking a look at `ProducesActionPotentials` capability which requires the model to provide a `neo.core.AnalogSignalArray`. The latest version of neo (0.5) no longer has `AnalogSignalArray` and simply uses `AnalogSignal` for the same. The capability might therefore need to be updated appropriately.

**Comment by rgerkin** [comment]
Yes, right now there is a hard dependency for neo 0.4.  I plan to move to neo 0.5 soon.

**Comment by rgerkin** [comment]
Fixed in aa45cb7
