### ISSUE TITLE
new changes to backends, NEURON introduces a lot of problems.

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/neuronunit#69]
In the file backends.py, the implementation of the function [def set_run_params(self, **params)](https://github.com/scidash/neuronunit/blob/dev/neuronunit/models/backends.py#L274-L286) is too simplistic, and does not work.

If I run the code block without modification I get the errors, which is indicative of the nested dictionaries not being processed properly:
Ie `//izhikevich2007Cell` is not supposed to appear anywhere in that hoc variable assignment string:
```
**Ignoring included LEMS file: Networks.xml
Ignoring included LEMS file: Simulation.xml
0.03
NEURON: syntax error
 near line 1
 m_RS_RS_pop[0].//izhikevich2007Cell={'a': 0.029999999999999999}
```
When I execute the following code within the set_run_params method
```
    def set_run_params(self, **params):
        self.params.update(params)
        for v in self.params.values():
             print(type(v))
             if type(v) is not bool and type(v) is not str:
                 paramdict = list(v.values())[0]
```
I see that the type of `v` varies three times, but it would be preferable if its type was consistently dictionary.

To paraphrase the return type of `params.values()` does not consist of exclusively dictionary types, but it also now contains exactly one boolean, and one string at its end, such that the dictionary `params`, would need cleaning before it could be used for assignments to `hoc` variables as intended in that code block.

There seems to be a lot going on here, and I will revert to an older version of this file for the time being.

**Comment by rgerkin** [comment]
I didn't even really change that much.  Most of it is your code.

**Comment by russelljjarvis** [comment]
These are some of the relevant changelogs:
https://github.com/scidash/neuronunit/commit/3142d6eb5e3abdfcd2abdea115d81d5b7ab7cda9

https://github.com/scidash/neuronunit/commit/99267f8f6e1222e720b8daf6ec4f54690e0e9363

https://github.com/scidash/neuronunit/commit/e17a1c21779df39653a5150a4404610f4384ae96

https://github.com/scidash/neuronunit/commit/fe9168154d538a38aa85dba2548d933c22d1cfdc

https://github.com/scidash/neuronunit/commit/70e3811f28b2c771d2fe20657fef36052ffda3c4

https://github.com/scidash/neuronunit/commit/31e623b38fa3b855bd434a636a7c777a66a113a0

https://github.com/scidash/neuronunit/commit/4aa609c9ad3c52b9cf16c26090b46b1d42db0410

**Comment by rgerkin** [comment]
Feel free to work with your code on `russel_dev` or your fork, and then we can commit it to `scidash/dev` when you and I have time to work through it.

**Comment by russelljjarvis** [comment]
Yes, I am happy to fix these problems now that I know they are a priority. I should have noted that I can see how the changes you made make the code better. I will work on integration, and finding the minor changes required to get all the functions working together.
.

**Comment by russelljjarvis** [comment]
I have adapted my example `exhaustive_search.py` (however note, this does not mean I have also adapted nsga.py) code to work with the new implementation of the file backends.py, especially with regards to the function [def set_run_params(self, **params)](https://github.com/scidash/neuronunit/blob/dev/neuronunit/models/backends.py#L274-L286)

However I stumped by the error below. Inserting the statement: `score_type = scores.ZScore`, into the InputResistanceTest class definition, does not work, and the class does contain `compute_score` method definition.
```
Executing test InputResistanceTest on model vanilla a0.03... Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/_control.py", line 150, in runFuture
    future.resultValue = future.callable(*future.args, **future.kargs)
  File "/opt/conda/lib/python3.5/runpy.py", line 254, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/opt/conda/lib/python3.5/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/opt/conda/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "exhaustive_search.py", line 92, in <module>
    score_matrixt=list(futures.map(gs.func2map,iter_))#list_of_models,rhstorage))
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/futures.py", line 99, in _mapGenerator
    for future in _waitAll(*futures):
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/futures.py", line 360, in _waitAll
    for f in _waitAny(future):
  File "/opt/conda/lib/python3.5/site-packages/scoop-0.7.2.0-py3.5.egg/scoop/futures.py", line 337, in _waitAny
    raise childFuture.exceptionValue
NotImplementedError: Test InputResistanceTest either implements no compute_score method or provides no score_type with a compute method.

Executing test InputResistanceTest on model vanilla... [2017-06-03 00:15:39,054] launcher  (127.0.0.1:33069) INFO    Root process is done.
[2017-06-03 00:15:39,055] launcher  (127.0.0.1:33069) INFO    Finished cleaning spawned subprocesses.

**Comment by rgerkin** [comment]
Fixed.
