### ISSUE TITLE
Unit tests with arguments

### ISSUE THREAD

**Issue by rgerkin** [scidash/neuronunit#70]
@russelljjarvis 
When I try to run your unit tests, I get errors like:  
```
======================================================================
ERROR: test_build_single (unit_test.showcase_tests.OptimizationTestCase)
----------------------------------------------------------------------
TypeError: test_build_single() missing 1 required positional argument: 'rh_value'

======================================================================
ERROR: test_main (unit_test.showcase_tests.OptimizationTestCase)
----------------------------------------------------------------------
TypeError: test_main() missing 1 required positional argument: 'ind'

----------------------------------------------------------------------
```
Ignore for now that they are in a different location.  The main concern is that they take arguments (like `rh_value` and `ind`) but I don't see how they are supposed to get these arguments passed to them.  Was this just a placeholder for unit tests that you planned to finish later, or is there some way that these arguments were getting passed when you ran them with `python -m unittest`?

**Comment by russelljjarvis** [comment]
Yes I planned to finish those unit tests later. I never finished them.

**Comment by rgerkin** [comment]
@russelljjarvis I think this has been taken care of, right?
