### ISSUE TITLE
Why aren't models/backends.py and neuron/models.py merged?

### ISSUE THREAD

**Issue by JustasB** [scidash/neuronunit#77]
Both of these files contain similar (e.g. copy & pasted) code:

https://github.com/scidash/neuronunit/blob/dev/neuronunit/models/backends.py
https://github.com/scidash/neuronunit/blob/dev/neuronunit/neuron/models.py

One of these needs to be removed and merged into the other. Is the NEURONBackend class only usable for the rheobase search project? If so, what is the reason why code was copied from neuron/models.py instead of being reused & modified via inheritance or nested classes?

Also related, to continue using the backend paradigm, shouldn't the neuroconstruct folder be moved under models/backends as well?

CC @rgerkin @russelljjarvis

**Comment by rgerkin** [comment]
@JustasB @russelljjarvis 
We are on a merge and purge mission for the next few days as we move towards the next release.  I propose that all the code should be in NEURONBackend and that the neuron module should be deleted.  But not before all of its useful components have been incorporated into that Backend.  

The neuroConstruct interface is being deprecated, as it is too hard to support (requires a bridge from Python to Java, among other nightmares).  However, some of the model classes there still make some sense (e.g. instantiating models directly from OSB projects).  That part probably needs to be refactored into some new models submodule, and all the Jython interface stuff can be moved into a new package separate from NeuronUnit.  

I will take care of the stuff in the second paragraph.  Russell, maybe you can do the stuff in the first paragraph with some consulting from Justas.

**Comment by JustasB** [comment]
Sounds good. @russelljjarvis, let me know how I can help.

**Comment by russelljjarvis** [comment]
The only reason, is that I was too scared to edit the main scidash repository. I will try after video call.

**Comment by rgerkin** [comment]
@russelljjarvis has removed the neuron folder in his branch and this will be merge into dev soon.

**Comment by russelljjarvis** [comment]
I think the next step is to test backends NEURON to see if it can be substituted in the following files.
https://github.com/JustasB/MitralSuite/blob/master/helpers.py

https://github.com/JustasB/MitralSuite/blob/master/SimpleNeuronCellTests.ipynb

**Comment by rgerkin** [comment]
@JustasB Can you work with Russell to make sure that the code he now has in "NEURONBackend" is able to do the kinds of things that you are doing with MitralSuite?  I want to make sure that the upcoming release of NeuronUnit can still run MitralSuite.

**Comment by russelljjarvis** [comment]
Hi @JustasB 
I have added the class HasSegment(sciunit.Capability) class has been added back into the dev branch of [backends](https://github.com/scidash/neuronunit/blob/dev/neuronunit/models/backends.py#L19-L35
).py

But I don't expect it to work yet, I am trying to modify the file 'helpers.py' from your mitralSuite repository, such that invocations of the SingleCellModel class can be replaced with ReducedModel with backend set to NEURON.

What I am seeing is that the SingleCellModel Class with the same constructor signature still needs to exist somewhere, and it probably should stay untouched. It reads:
``` python
class SingleCellModel(NeuronModel, \
                                    HasSegment, \
                                    ProducesMembranePotential, \
                                    ReceivesSquareCurrent, \
                                    ProducesActionPotentials, \
                                    ProducesSpikes):
```, and I should probably keep it as is.
 
The class NeuronModel needs to inherit all if its methods from backends.py class  such that it reads:
```NeuronModel(NEURONBackend)``` instead of: ```class NeuronModel(sciunit.Model):```

My test for whether these changes work or not might involve repurposing code helpers.py such, models instanced with SingleCellModel signature should still work.
 
https://github.com/russelljjarvis/MitralSuite/blob/master/helpers.py#L48-L68

```python

     

    mod1 = SingleCellModel(hVar = h, \
                           section = soma, \
                           loc = 0.5, # Current and voltage injection and measurement location on the section \
                           name = "SimpleHHCellModel")
    mod1.setTimeStep(1/32.0 * ms)
    mod1.setStopTime(2*s)
 ```  
 
``` python
    mod1 = SingleCellModel(NeuronModel, \
                                    HasSegment, \
                                    ProducesMembranePotential, \
                                    ReceivesSquareCurrent, \
                                    ProducesActionPotentials, \
                                    ProducesSpikes)

```

**Comment by russelljjarvis** [comment]
Hi @JustasB and @rgerkin, as discussed this morning I have made the proposed changes to neuronunit/models/backends.py such that it is compatible with code in https://github.com/russelljjarvis/MitralSuite/blob/master/helpers.py#L48-L68

I also created an example notebook of this code working, which is located in scratch directory of 
branch -dev of scidash/neuronunit
https://github.com/scidash/neuronunit/blob/dev/scratch/example_neuron_backend.ipynb

Some pitfalls to lookout for Justas:
Rick has converted your method signatures from CamelCase to underscore_lower_case, as I am guessing this is PEP8 compliant.

For example: 
```python
SetIntegrationMethod(self, method = "fixed"):
```
Is now:
```python 
def set_integration_method(self, method = "fixed"):
```
Also NEURONs internal syntax for setting and manipulating the ODE solver property has changed such that you have to instantiate an object from the CVode() class. I don't know if this is really that dissimilar to the previous case, but its more I the cvode attribute could not be modified it unless I instantiated it as below:

```
    try:
            assert self.cvode.active()
        except:
            self.cvode = self.h.CVode()
            self.cvode.active(1 if method == "variable" else 0)
```

**Comment by JustasB** [comment]
Thank you @russelljjarvis, I will take a look

**Comment by JustasB** [comment]
@russelljjarvis Looking at the[ code in scratch folder](https://github.com/scidash/neuronunit/blob/dev/scratch/example_neuron_backend.ipynb), I was able to create a simple model to using the [SingleCellModel(NEURONbackend)](https://github.com/scidash/neuronunit/blob/dev/neuronunit/models/backends.py#L404), but ran into several problems when running a test:

 - The test first complained that [models.backends.Backend](https://github.com/scidash/neuronunit/blob/dev/neuronunit/models/backends.py#L23) does not inherit from sciunit.Model (this seems to be a requirement for all neuronunit tests)
 - Then it did not like the quantities format for [passing params into the inject_square_current method](https://github.com/scidash/neuronunit/blob/dev/neuronunit/models/backends.py#L354) (I'm using the quantities format eg: t=2 * ms, which should be trivially convertible to any desired unit scale)

I see there is large pull request pending to be merged into the dev branch with many changes to the backends.py. I don't want to make the changes that would get the mitral suite to work with NEURONbackend until your pr is merged.

But right now, NEURONbackend does not appear to be compatible with the mitral suite.

Does the following code run on your machine? It's the[ basic test from mitral suite](https://github.com/JustasB/MitralSuite/blob/master/SimpleNeuronCellTests.ipynb) with the pythonized method signatures.
```
import neuron
from quantities import s, ms, nA, mV
from neuronunit.models.backends import SingleCellModel
from neuronunit.tests import InjectedCurrentAPWidthTest

# Build a single compartment HH model
soma = neuron.h.Section()
soma.L = 100
soma.diam = 100
soma.cm = 10
soma.Ra = 180
soma.insert("pas")
soma.insert("hh")

# Set up the simulation
mod1 = SingleCellModel(neuronVar=neuron,
                       section=soma,
                       loc=0.5,  # Current and voltage injection and measurement location on the section \
                       name="SimpleHHCellModel")

mod1.set_integration_method("fixed")
mod1.set_time_step(1 / 128.0 * ms)  # 2^-n are preferable
mod1.set_stop_time(2 * s)

# Inject some current and measure the ap width
i_ap = {'amplitude': 20 * nA, 'delay': 1 * s, 'duration': 5 * ms}

t1 = InjectedCurrentAPWidthTest({'mean': 1.5 * ms, 'std': 0.5 * ms})  # Example values
t1.params = {'injected_square_current': i_ap}
t1.judge(mod1)

```

**Comment by russelljjarvis** [comment]
Hi @JustasB and @rgerkin,

I will try to test this out soon.

Russell.

**Comment by rgerkin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Backends problems](https://trello.com/c/AE2J6O4z/37-backends-problems)

**Comment by rgerkin** [comment]
Finished in russelljjarvis/neuronunit@dev, will be finished when the pull request from there is merged.
