### ISSUE TITLE
possible typo in neuronunit/__init__.py

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/neuronunit#82]
Should line 225 of exponential fit read:
```vm_fit[offset:] = a * np.exp(-t[offset:]/b) + c```
as opposed to:
```vm_fit[offset:,0] = a * np.exp(-t[offset:]/b) + c```

Since the dimesions of vm_fit do not permit multiple indexs.

Its in context here:
https://github.com/scidash/neuronunit/blob/dev/neuronunit/tests/__init__.py#L225

**Comment by rgerkin** [comment]
Requires neo 0.5 to work.
