### ISSUE TITLE
When the `score.sort_key` scheme breaks down.

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/neuronunit#96]
Hi @rgerkin with regards to the email today I finally figure out the problem.

As you said over google VOIP, 

`score.sort_key` gives badness conveniently normalized between [0,1] The closer to zero the less badness. 

`float(score.raw)` gives goodness as distance from zero in either +ve or -ve directions. so `np.abs(float(score.raw))` gives an un-normalized goodness in the +ve direction.

It almost always works to use `score.sort_key` as the error except its not fine to use it on the Rheobase ratio score as it approaches zero.

When Rheobase approaches zero score raw is 0.09 and score.sort_key becomes actually `0` which is really bad, as the GA treats `0` as zero error, and is naturally attracted to creating genes that produce this state, which explains why all the candidate models produce a rheobase spike as they approach a current injection value of 0pA.

I feel that the problem is the real error value I want in the rheobase case is more like `1.0/np.abs(float(score.raw))`.

```
print(score)
out: Ratio = 0.09
print(score.sort_key)
out 0
```   

I was thinking it would be good to create a unit test that measures the co-variance between 

score.sort_key

**Comment by rgerkin** [comment]
@russelljjarvis 

1) What email today?  

2) No, I keep emphasizing that higher `sort_key` is better.  1 is the best.  0 is the worst.  The thing to minimize is always `-sort_key`.  Then you will find solutions with sort_key closest to 1, e.g. `RatioScores` close to 1 and `ZScores` close to 0.  

3) The RatioScore works by dividing the observed by the predicted, see [here](https://github.com/scidash/sciunit/blob/dev/sciunit/scores.py#L180).  The observed is fixed, i.e. it comes from the data.  As the model rheobase goes towards zero, the RatioScore will go towards 0, and the sort_key will decrease as well.  You can play around with this example:  

```python
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
observed_rheobase = 100.0
predicted_rheobases = np.linspace(0.1,300,1000)
sort_keys = []
for predicted_rheobase in predicted_rheobases:
    sort_keys.append(RatioScore(predicted_rheobase/observed_rheobase).sort_key)
plt.plot(predicted_rheobases,sort_keys)
plt.xlabel("Predicted Rheobase")
plt.ylabel("Sort Key")
plt.title("Example with observed rheobase = %.1f" % observed_rheobase)
```

One possible issue is that in the implementation I had, the `sort_key` reached 0 before the ratio itself reaches 0, as you might be able to see from the example above (depending on the version of sciunit you are working with).  So the optimizer might have difficulty finding the gradient once it tested models with sufficiently small rheobase.  I changed this in the most recent sciunit commit so now `sort_key` should be a non-zero gradient for any positive value of the prediction (i.e. any positive rheobase).  

4) If the predicted (i.e. model) rheobase is ever 0 or negative, you will get an error when the RatioScore is instantiated, e.g. `RatioScore(0.0)` will raise the error: `InvalidScoreError: RatioScore was initialized with a score of 0.000000, but a RatioScore must be positive.`

5) I am still unconvinced that, if you understand `sort_key`, that you will need to use any fancy function of the score.  You should just be able to maximize `sort_key` or rather minimize `-sort_key`.  

6) Your final thought seems unfinished.  The co-variance between what and what?

**Comment by russelljjarvis** [comment]
Yes, in your words the issue I am experiencing is: One possible issue is that in the implementation I had, the sort_key reached 0 before the ratio itself reaches 0, as you might be able to see from the example above (depending on the version of sciunit you are working with). So the optimizer might have difficulty finding the gradient once it tested models with sufficiently small rheobase. I changed this in the most recent sciunit commit so now sort_key should be a non-zero gradient for any positive value of the prediction (i.e. any positive rheobase).


Another source of confusion when writing about this issue is coming from a convention in deap use, where you declare multiplicative weights for the error outside of the evaluate function, so I forgot to make explicit that elsewhere in the code there is a declaration:
```
creator.create("FitnessMin", base.Fitness, weights=(-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0))
```
Where these weights are multiplied by the error after the error is evaluated. 

Another source of confusion is the directionality and semantics of the word fitness (to most people fitness implies goodness). 

If an outsider was to read over my code without evaluating it, they would probably expect that the program would maximize badness by minimizing small numbers that are multiplied by -1.0 (under the most basic definition, minimization can mean increasing the magnitude of a negatively signed number), by contrast what actually happens is that the 'FitnessMin function', only means minimize the order of magnitude of the number which is what I want in this case, but its challenging to understand just by reading the code.

For the purposes of generating plots for the poster I have temporarily substituted into the rheobase test `np.abs(np.abs(observation) - np.abs(prediction))`, so at least I can generate plots of what the output should be, and then I can work forwards to using the sciunit z-score from there.

**Comment by rgerkin** [comment]
With the sort_key fixed you won't need to do this sort of thing.  We will want to avoid having non-dimensionless quantities in the objective functions, since then they depend on units (e.g. pA vs nA).
